name: Build and Release

on:
  push:
    tags:
      - 'v*'  # Push events to matching v*, i.e. v1.0, v20.15.10

# Add permissions configuration
permissions:
  contents: write

jobs:
  build:
    name: Build Binary
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: example-cli-linux-amd64
            asset_name: example-cli-linux-amd64
          - os: ubuntu-latest
            artifact_name: example-cli-linux-arm64
            asset_name: example-cli-linux-arm64
            build_args: --platform linux/arm64
          - os: macos-latest
            artifact_name: example-cli-darwin-amd64
            asset_name: example-cli-darwin-amd64
          - os: windows-latest
            artifact_name: example-cli-windows-amd64.exe
            asset_name: example-cli-windows-amd64.exe

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install PyInstaller
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller

    - name: Build Binary
      run: |
        pyinstaller --onefile src/example_cli/cli.py --name ${{ matrix.artifact_name }}

    - name: Upload Release Asset
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: dist/${{ matrix.artifact_name }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 